version: "3"

volumes:
  dados:

services:
  ui:
    ports:
      - 80:80
    depends_on:
      - api
  
  api:
    healthcheck:
      test: ["CMD-SHELL", "curl -fhttp://api:8080/healthycheck && echo 'OK'"]
      interval: 10s
      timeout: 2s
      retries: 6
    depends_on:
      - postgres
    
  postgres:
    image: postgres:9.6
    volumes:
      # Volume de dados
      - dados:/var/lib/postgresql/data
    # command: postgres -c 'max_connections=2000'
    ports:
      - 5432:5432
    environment:
      - TZ=America/Fortaleza
      - DB_NAME=estatus
      - DB_USER=postgres
      - DB_PASS=postgres
